name: Close Stale Issues
on:
  schedule:
    - cron: "0 0 * * *" # runs daily

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Close Stale Issues
        uses: actions/stale@v9.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 7 # mark issues and PRs as stale after 7 days of inactivity
          days-before-close: 7 # close stale issues and PRs after 7 more days
          stale-issue-message: "This issue has been marked as stale due to inactivity."
          close-issue-message: "This issue has been closed due to inactivity."
          stale-pr-message: "This pull request has been marked as stale due to inactivity."
          close-pr-message: "This pull request has been closed due to inactivity."
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          exempt-issue-labels: "keep-open"
          exempt-pr-labels: "keep-open"
          remove-stale-when-updated: true
